### ISSUE TITLE
Source Legality

### ISSUE THREAD

**Issue by Shadow53** [NachiketaVadera/EBookDownloader#8]
I was trying out this app when I noticed that it made C. J. Archer's Glass and Steele series freely available.

Thing is, she sells these books on Smashwords, so I don't see how she'd also be okay with them being available to download for free from some other website.

It might be a good idea to limit access to known repositories of only freely available books (e.g. Gutenburg) to avoid enabling piracy.

**Comment by NachiketaVadera** [comment]
Hey @Shadow53. Thank you for trying out the app!

I completely understand your concern and how this is a problem. I am trying to find a list of sources that can match up closely to VK and I'll make the swap as soon as I'm sure that there won't be a setback among the users.

My only current source now is VK and they are compliant of author's requests to remove copyrighted content and so that's all I have to offer at this movement. 

Feel free to suggest better sources and thanks again for trying out the app.
